name = "MakiePresentation"
uuid = "ae6fd361-813c-416e-999f-1b904798b73f"
authors = ["ffreyer <frederic481994@hotmail.de> and contributors"]
version = "0.1.0"

[deps]
Makie = "ee78f7c6-11fb-53f2-987a-cfe4a2b5a57a"

[compat]
Makie = "0.17"
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
