name = "MakiePresentation"
uuid = "ae6fd361-813c-416e-999f-1b904798b73f"
authors = ["ffreyer <frederic481994@hotmail.de> and contributors"]
version = "0.1.0"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
